### ISSUE TITLE
need semver key for files - how to do that?

### ISSUE THREAD

**Issue by sdole** [bazaarvoice/s3-upload-maven-plugin#13]
I want to be able to upload files to S3 under a key that is dynamically generated using the groupId-artifactId-version of the project. Is that possible? If not, are you still actively accepting pull requests - if I were to make this change?

Thanks!

**Comment by matthewbogner** [comment]
It is already possible.  Example configuration of the plugin:

```xml
<configuration>
  <bucketName>my-bucket</bucketName>
  <source>core/target/rpm/${project.artifactId}/RPMS/noarch/${project.artifactId}-${project.version}-1.noarch.rpm</source>
  <destination>path/to/${project.artifactId}-${project.version}-1.noarch.rpm</destination>
</configuration>
```

**Comment by matthewbogner** [comment]
But FWIW, I've found it is much more straightforward to just use the AWS CLI to "aws s3 cp" the file you want at the end of the build (assuming you are using jenkins or something similar)

**Comment by sdole** [comment]
thanks for the quick reply.
